---
services: docker

env:
  - distro: ubuntu1804

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  email: lg@cloudjourneyman.com
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  